c
  public class Const {
  public static final int SUCCESS = 1;
  public static final int FAIL = 0;
  
  public static final int SIGN_IN_SUCCESS = 1;
  public static final int UPW_NOT_MATCHED = 2;
  public static final int UID_NOT_EXIST = 3;

}
  public class Const {
  public static final int SUCCESS = 1;
  public static final int FAIL = 0;
  
  public static final int SIGN_IN_SUCCESS = 1;
  public static final int UPW_NOT_MATCHED = 2;
  public static final int UID_NOT_EXIST = 3;

}
  public class Const {
  public static final int SUCCESS = 1;
  public static final int FAIL = 0;
  
  public static final int SIGN_IN_SUCCESS = 1;
  public static final int UPW_NOT_MATCHED = 2;
  public static final int UID_NOT_EXIST = 3;

}
  public class Const {
  public static final int SUCCESS = 1;
  public static final int FAIL = 0;
  
  public static final int SIGN_IN_SUCCESS = 1;
  public static final int UPW_NOT_MATCHED = 2;
  public static final int UID_NOT_EXIST = 3;

}
  public class Const {
  public static final int SUCCESS = 1;
  public static final int FAIL = 0;
  
  public static final int SIGN_IN_SUCCESS = 1;
  public static final int UPW_NOT_MATCHED = 2;
  public static final int UID_NOT_EXIST = 3;

}
